name: MERN CI/CD Pipeline

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Node setup
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # FRONTEND TEST
      - name: Install & Test Frontend
        working-directory: ./Frontend
        run: |
          npm install
          npm test

      # BACKEND TEST
      - name: Install & Test Backend
        working-directory: ./backend
        run: |
          npm install
          npm test

      # DOCKER BUILD (IMPORTANT)
      - name: Build Docker Images
        run: |
          docker compose build