name: Node Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Test Frontend
        working-directory: ./Frontend
        run: |
          npm install
          npm test

      - name: Install and Test Backend
        working-directory: ./Backend
        run: |
          npm install
          npm test